permalink:           pretty

title:               inconvergent
tagline:             A Study of Generative Algorithms
url:                 http://inconvergent.net/
baseurl:             ""

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              Anders Hoff
  url:               https://twitter.com/inconvergent
  email:             inconvergent@gmail.com

version:             3.1.1
github:
  repo:              https://github.com/inconvergent

pages_list:
  Generative: '/generative'
  #Interactive: '/interactive'
  Gallery: '/gallery'
  Store: 'http://store.inconvergent.net'
  About: '/about'

generative-title: 'On Generative Algorithms'
store-title: 'Store'
