permalink:           pretty

title:               inconvergent
tagline:             A Study of Generative Algorithms
url:                 http://inconvergent.net/
baseurl:             ""

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              Anders Hoff
  url:               https://twitter.com/inconvergent
  email:             inconvergent@gmail.com

version:             3.1.1
github:
  repo:              https://github.com/inconvergent

pages_list:
  Generative: '/generative'
  Gallery: '/gallery'
  Store: 'http://store.inconvergent.net'
  About: '#about'

generative-title: 'On Generative Algorithms'
store-title: 'Store'

gallery_images:
  '/img/spline-circle.jpg': 'sand splines 2'
  '/img/creatures.jpg': 'sand creatures'
  '/img/ello-mesh3.jpg': 'differential mesh 1'
  '/img/ello-mesh2.jpg': 'differential mesh 2'
  '/img/ello-mesh.jpg': 'differential mesh 3'
  '/img/ello-mesh5.jpg': 'differential mesh 4'
  '/img/ello-mesh4.jpg': 'differential mesh 5'
  '/img/ello-line.jpg': 'sand splines'
  '/img/fracture_a.jpg': 'fractures 1'
  '/img/fracture_b.jpg': 'fractures 2'
  '/img/fracture_c.jpg': 'fractures 3'
  '/img/differential_d.jpg': 'differential 1'
  '/img/differential_c.jpg': 'differential 2'
  '/img/differential_f.jpg': 'differential 3'
  '/img/differential_line_b.jpg': 'differential.step 1'
  '/img/differential_line_c.jpg': 'differential.step 2'
  '/img/differential_line_d.jpg': 'differential.step 3'
  '/img/leaf3a.jpg': 'leaf 1'
  '/img/leaf3b.jpg': 'leaf 2'
  '/img/leaf3c.jpg': 'leaf 3'
  '/img/orbitals_ba.jpg': 'orbitals'
  '/img/orbitals_bb.jpg': 'orbitals 1'
  '/img/orbitals_aa.jpg': 'orbitals 2'
  '/img/imgb.jpg': 'orbitals 3'
  '/img/imgm.jpg': 'orbitals, box'
  '/img/imgc.jpg': 'orbitals 4'
  '/img/imgd.jpg': 'orbitals 5'
  '/img/imgn.jpg': 'orbitals, lines 1'
  '/img/imgo.jpg': 'orbitals, lines 2'
  '/img/imgl.jpg': 'orbitals 5'
  '/img/linetrace_tree_a.jpg': 'tree.linetrace'
  '/img/tree_c.jpg': 'tree 1'
  '/img/tree_d.jpg': 'tree 2'
  '/img/imgv.jpg': 'hyphae 1'
  '/img/imgr.jpg': 'hyphae 2'
  '/img/imgs.jpg': 'hyphae 3'
  '/img/hyphae_a.jpg': 'hyphae 4'
  '/img/hyphae_b.jpg': 'hyphae 5'
  '/img/imgp.jpg': 'linetrace 1'
  '/img/imgq.jpg': 'linetrace 2'
  '/img/imgu.jpg': 'linetrace 3'
  '/img/tracepath_sand.jpg': 'linetrace, sandstroke 1'
  '/img/tracepath_sand2.jpg': 'linetrace, sandstroke 2'

gems:
  - jekyll-redirect-from
